netgen_content_browser:
    item_types:
        # must match "value_types" key in netgen_layouts config
        doctrine_recipes:
            name: 'Recipes ğŸ“'
            preview:
                template: 'nglayouts/content_browser/recipe_preview.html.twig'
